plugins {
    id 'application'
}

group = 'com.gradualgames'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.dv8tion:JDA:6.5.0'

    implementation platform('com.fasterxml.jackson:jackson-bom:2.19.2')
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // JDA uses SLF4J. This gives you actual console logging.
    runtimeOnly 'ch.qos.logback:logback-classic:1.5.18'
}

application {
    mainClass = 'com.gradualgames.shopkeep.Shopkeep'
}